spring:
  application:
    name: backend
    
  profiles:
    active: dev
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  mvc:
    static-path-pattern: /static/**
    
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cachecontrol:
          max-age: 3600

server:
  port: 8080