spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ai_quizpic?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER:dev}
    password: ${MYSQL_PASSWORD:twig42489o}
    driver-class-name: com.mysql.cj.jdbc.Driver

  hikari:
    connection-timeout: 20000
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 300000
    max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # application.yml
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: VGhpcy1pcy1hLXNlY3JldC1rZXktd2l0aC1hdC1sZWFzdC0zMi1ieXRlcw==

  mvc:
    static-path-pattern: /static/**
    
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cachecontrol:
          max-age: 3600
          
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

clip:
  service:
    url: http://localhost:5000/validate
    
server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example: DEBUG
    org.springframework.web: DEBUG